### ISSUE TITLE
Unable to connect to Neo4j APOC Plugin

### ISSUE THREAD

**Issue by Kornspan** [kingjulio8238/Memary#51]
When I run the app, I get this error 
<img width="543" alt="image" src="https://github.com/kingjulio8238/memary/assets/126836392/68c02790-5dc7-43bf-99f9-89de9e09b297">
, I am unsure how to fix this.

**Comment by kevinl424** [comment]
Sorry for the late reply here, seems like this is an issue with Neo4j database configurations. APOC is just a library that Neo4j uses to add more functionality, with every Neo4j aura instance, APOC should be automatically integrated, but if you are hosting the instance on your own machine, you usually have to download and enable APOC manually. Are you connecting to an aura instance or is the database self hosted?

**Comment by shutter-cp** [comment]
```yaml
version: '3.7'
services:
  neo4j-v3:
    image: neo4j:5.21.2
    ports:
      - "27474:7474"
      - "27687:7687"
    environment:
      - NEO4J_AUTH=neo4j/root1234
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms.security.procedures.unrestricted=apoc.*
      - NEO4J_dbms.security.procedures.allowlist=apoc.*
    volumes:
      - ./neo4j_data:/data
      - ./plugins:/plugins
```

This can
